//: Textes de l'interface en anglais
Object.assign(I18N.en, {
  "play": "Play",
  "pause": "Pause",
  "silence": "Silence",
  "silence.title": "Clear all pulses in flight",
  "step": "Step",
  "volume": "Volume",
  "bpm.title": "One step is an eighth note: BPM = 30000 / step in ms",
  "status": "step {0} · pulses {1}",
  "status.midi": " · MIDI {0} notes",
  "status.audio": " · audio {0} s",
  "status.stopped": " (stopped)",
  "grid.aria": "Hexagram grid {0}x{1}",
  "menu.tonality": "Tonality",
  "menu.hexagrams": "Hexagrams",
  "menu.settings": "Settings",
  "menu.sound": "Sound",
  "menu.midi": "MIDI",
  "menu.file": "File",
  "menu.draw": "Draw",
  "menu.help": "Help",
  "tonic": "Tonic",
  "octave": "Octave",
  "octave.title": "Base octave: shifts every sound",
  "scaleBase": "Scale",
  "scaleBase.title": "Base scale: applied to all hexagrams and used for new ones",
  "tonality.hint": "The tonic and the octave transpose everything. Each hexagram can also have its own (Hexagrams menu or right-click).",
  "tonic.global": "global tonic",
  "set.range": "Soft line range",
  "set.mutate": "Line mutation",
  "set.rotAll": "↻ all",
  "set.rotAll.title": "Rotate every hexagram by 60° at each step",
  "set.uniform": "Uniform octave",
  "set.uniform.title": "Same octave on every row (otherwise the grid spans 3 octaves, low rows low)",
  "set.theme": "Theme",
  "theme.dark": "Dark",
  "theme.light": "Light",
  "theme.sepia": "Sepia",
  "theme.green": "Green",
  "snd.internal": "Internal sound",
  "snd.wave": "Wave",
  "snd.envTitle": "Drag the points: A, D + S, R",
  "snd.filter": "Filter",
  "snd.envDepth.title": "Depth of the envelope that opens the filter (follows A D S R)",
  "snd.reset": "Default sound",
  "wave.square": "square",
  "wave.triangle": "triangle",
  "wave.sawtooth": "sawtooth",
  "wave.sine": "sine",
  "filter.lowpass": "low-pass",
  "filter.highpass": "high-pass",
  "filter.bandpass": "band-pass",
  "filter.notch": "notch",
  "midi.enable": "Enable MIDI",
  "midi.noout": "(no output)",
  "midi.none": "no MIDI output detected",
  "midi.denied": "MIDI access denied",
  "midi.nofile": "Web MIDI is missing on file:// (Firefox): serve the page, see Help",
  "midi.unavail": "Web MIDI unavailable in this browser (try Chrome, Edge or Firefox)",
  "file.rec": "Recording",
  "file.names": "File name",
  "file.setup": "Setup",
  "rec.midi": "Record MIDI",
  "rec.midi.title": "Records the notes (until you save)",
  "rec.save": "Save the recording",
  "rec.save.midi.title": "Stops recording and downloads the .mid file",
  "rec.audio": "Record audio",
  "rec.audio.title": "Records the internal sound (until you save)",
  "afmt.title": "File format",
  "rec.save.audio.title": "Stops recording and downloads the audio file",
  "recmsg.midi.on": "MIDI recording in progress.",
  "recmsg.midi.off": "MIDI recording stopped: it still has to be saved.",
  "recmsg.midi.saved": "MIDI file downloaded.",
  "recmsg.midi.none": "Nothing to save: no note recorded.",
  "recmsg.audio.on": "Audio recording in progress.",
  "recmsg.audio.wait": "Audio recording in progress (it starts at the first Play).",
  "recmsg.audio.off": "Audio recording stopped: it still has to be saved.",
  "recmsg.audio.none": "Nothing to save: no sound recorded.",
  "recmsg.audio.saved": ".{0} file downloaded ({1} s).",
  "setup.name.title": "Setup name",
  "setup.save": "Save",
  "setup.save.title": "Keep in the browser memory",
  "setup.load": "Load",
  "setup.del": "Delete",
  "setup.file": ".json file",
  "setup.file.title": "Download a .json file",
  "setup.open": "Open...",
  "setup.open.title": "Open a .json or .txt file",
  "setup.text.ph": "The setup as text: copy / paste here",
  "setup.copy": "Text / Copy",
  "setup.copy.title": "Writes the current setup in the box and copies it",
  "setup.apply": "Apply",
  "setup.apply.title": "Load the setup written in the box",
  "setup.empty": "(nothing in memory)",
  "setup.text": "Text",
  "setup.msg.error": "Error: {0}",
  "setup.msg.loaded": "{0} loaded.",
  "setup.msg.saved": "\"{0}\" kept in memory.",
  "setup.msg.nostore": "Browser memory unavailable: use the file or the text.",
  "setup.msg.nothing": "Nothing to load.",
  "setup.msg.deleted": "\"{0}\" deleted from memory.",
  "setup.msg.file": "File {0}.json downloaded.",
  "setup.msg.copied": "Text copied to the clipboard.",
  "setup.msg.manual": "Text written in the box: copy it by hand (Ctrl+C).",
  "err.json": "unreadable text (invalid JSON)",
  "err.notsetup": "this is not a Hexacorde setup",
  "err.max": "{0} hexagrams at most",
  "err.pos": "{0}: invalid position (integers from 0 to {1} for the column, 0 to {2} for the row)",
  "err.occupied": "{0}: position already taken",
  "err.lines": "{0}: \"traits\" (6 or 7 digits 0 or 1) or \"numero\" (1 to 64) expected",
  "err.chan": "{0}: channel from 1 to 16",
  "err.speed": "{0}: unknown speed \"{1}\" (x1 x2 x3 /2 /3 /4 /8)",
  "err.angle": "{0}: angle must be a multiple of 60",
  "err.notes": "{0}: notes: \"plein\" and \"brise\" = as many values as lines (6 or 7), from 0 to 23 semitones (null = silence)",
  "err.scale": "{0}: unknown scale \"{1}\"",
  "draw.random": "Draw lines at random",
  "draw.random.title": "Draws the lines of every hexagram at random",
  "draw.scatter": "Scatter at random",
  "draw.scatter.title": "Moves the hexagrams to random points of the grid",
  "hex.title": "Hexagram",
  "act.title": "Active: untick to grey the hexagon out",
  "del.title": "Delete this hexagon",
  "scale.title": "Scale",
  "chan.title": "MIDI channel",
  "stonic.title": "Tonic of this hexagon",
  "soct.title": "Octave of this hexagon (added to the global octave)",
  "rot": "rot.",
  "rot.title": "Make this hexagon rotate",
  "dir.title": "Rotation direction",
  "spd.title": "Rotation speed",
  "reset": "Reset",
  "reset.title": "Put this hexagram back to its starting form",
  "loop.every": "prime every",
  "steps": "steps",
  "loop.title": "Prime a note of this hexagon every N steps",
  "seven": "7th side",
  "seven.title": "Adds a 7th side: the hexagon becomes a heptagon",
  "m.hex": "Hexagram",
  "m.scale": "Scale",
  "m.chan": "MIDI channel",
  "m.tonic": "Tonic",
  "m.oct": "Octave",
  "m.rot": "Rotation",
  "m.rot.active": "active",
  "m.sides": "Sides",
  "m.seven": "7th side (heptagon)",
  "m.loop": "Priming",
  "m.loop.every": "every",
  "m.turn": "Turn",
  "m.ccw.title": "Turn by 60° counterclockwise",
  "m.cw.title": "Turn by 60° clockwise",
  "m.custom": "Custom notes",
  "m.hint": "Scale {0}, tonic {1}",
  "m.line": "line",
  "m.solid": "solid",
  "m.broken": "broken",
  "m.silence": "· silence",
  "m.tonicMark": " (tonic)",
  "m.fill": "Reload the scale",
  "m.fill.title": "Copies the notes of the current scale",
  "m.shuffle": "Shuffle the order",
  "m.shuffle.title": "Randomly changes which line gets which note, including the scale note that has no solid line",
  "m.deactivate": "Deactivate",
  "m.activate": "Activate",
  "m.deact.title": "Grey the hexagon out: it neither plays nor receives",
  "m.delete": "Delete",
  "m.close": "Close",
  "sel.title": "{0} hexagrams selected",
  "sel.clear": "Deselect",
  "board.title": "Grid {0}x{1}",
  "board.add": "New hexagram here",
  "board.add.title": "Adds a random hexagram on the nearest free point",
  "board.size": "Size",
  "board.cols": "columns",
  "board.rows": "rows",
  "board.apply": "Apply",
  "board.hint": "columns x rows, from {0} to {1}",
  "board.nofit": "Not possible: a hexagon lies outside the new grid (sizes {0} to {1})",
  "board.delsel": "Delete selection ({0})",
  "board.delsel.title": "Deletes the selected hexagrams",
  "scale.chromatique": "Chromatic",
  "scale.chromatique.s": "chr",
  "scale.majeur": "Major",
  "scale.majeur.s": "maj",
  "scale.mineur": "Natural minor",
  "scale.mineur.s": "min",
  "scale.dorien": "Dorian",
  "scale.dorien.s": "dor",
  "scale.phrygien": "Phrygian",
  "scale.phrygien.s": "phr",
  "scale.lydien": "Lydian",
  "scale.lydien.s": "lyd",
  "scale.mixolydien": "Mixolydian",
  "scale.mixolydien.s": "mix",
  "scale.locrien": "Locrian",
  "scale.locrien.s": "loc",
  "scale.mineurharm": "Harmonic minor",
  "scale.mineurharm.s": "hmi",
  "scale.mineurmel": "Melodic minor",
  "scale.mineurmel.s": "mmi",
  "scale.tons": "Whole tone",
  "scale.tons.s": "ton",
  "scale.blues": "Blues",
  "scale.blues.s": "blu",
  "scale.pentamajeur": "Major pentatonic",
  "scale.pentamajeur.s": "pM",
  "scale.pentamineur": "Minor pentatonic",
  "scale.pentamineur.s": "pm",
  "scale.hongrois": "Hungarian minor",
  "scale.hongrois.s": "hon",
  "scale.phrygiendom": "Phrygian dominant",
  "scale.phrygiendom.s": "pdo",
  "scale.doubleharm": "Double harmonic",
  "scale.doubleharm.s": "dbh",
  "scale.dim12": "Diminished (half-whole)",
  "scale.dim12.s": "dm1",
  "scale.dim21": "Diminished (whole-half)",
  "scale.dim21.s": "dm2",
  "scale.insen": "In sen (Japanese)",
  "scale.insen.s": "ins",
  "scale.hirajoshi": "Hirajoshi",
  "scale.hirajoshi.s": "hir",
  "scale.bebop": "Bebop dominant",
  "scale.bebop.s": "beb",
  "scale.augmentee": "Augmented",
  "scale.augmentee.s": "aug",
  "help.1": "<b>Click</b> a hexagon to prime it (this starts the clock). <b>Drag</b> its body to move it onto a free grid point. <b>Click a line</b> to toggle it solid / broken. <b>Drag a line</b> to rotate the hexagon in 60° steps; the <b>mouse wheel</b> does the same.",
  "help.2": "<b>Notes (chromatic)</b>: line 1 (top) C / C#, then clockwise D / D#, E / F, F# / G, G# / A, A# / B (in French: do / do#, ré / ré#...). Solid = natural note, broken = note + 1 semitone. The octave depends on the grid row.",
  "help.3": "<b>Notes (scales)</b>: side k plays degree k+1 of the scale (past the last note, it wraps up an octave). Solid line: the note is played and sent back. Broken line: silence, nothing is sent back, but pulses received always pass through. There are 23 scales.",
  "help.4": "<b>Sending</b>: each played line sends a pulse in its direction, toward the first hexagon of the sector. The farther it is, the more steps it takes.",
  "help.5": "<b>Solid line</b>: strong pulse, unlimited range; on arrival the side hit bounces (the hexagon starts to play). <b>Broken line</b>: soft pulse, short range; on arrival it passes through the hexagon without making it sound.",
  "help.6": "<b>Name</b>: each hexagram shows its number and its I Ching name (King Wen order). Line 1 of the hexagon is read as the first line of the hexagram (the bottom one in tradition); lines 4 to 6 form the upper trigram.",
  "help.7": "<b>Right-click a hexagon</b>: all its settings (hexagram, scale, channel, tonic, octave, rotation, 7th side, priming every N steps, reset), a 60° step, the <b>custom notes</b> (pick the note of the solid and of the broken line for each side, silence allowed; the notes of the scale are marked ● and coloured), <b>Reload the scale</b>, <b>Shuffle the order</b>, and <b>Deactivate</b> (greyed: it neither plays nor receives) or <b>Delete</b>.",
  "help.8": "<b>Right-click the grid</b>: add a new hexagram (random lines, the global scale and tonic) on the nearest free point, or set a custom grid size (columns x rows, 3 to 12 each). The grid spans 3 octaves, low rows low (tick <i>Uniform octave</i> in Settings for the same octave everywhere).",
  "help.9": "<b>Selection</b>: drag a rectangle on the empty grid to select several hexagrams (Shift adds, a click on the background clears). Right-click one of them to delete, deactivate or activate them all; the Delete key deletes too.",
  "help.10": "<b>Tonality</b> menu: tonic, octave and base scale for everything. Choosing a scale there applies it to all hexagrams and to the ones you add later. Each hexagram may override the tonic and add its own octave.",
  "help.11": "<b>Rotation</b> (per hexagon, in the Hexagrams menu): the hexagon turns in 60° steps. Speed ×1 = one 60° step per clock step, ×2 and ×3 = two or three, ÷2 to ÷8 = one step every 2 to 8 clock steps. Each line keeps its note, but its sending direction and the side hit on reception change. <b>7th side</b>: the hexagon becomes a heptagon (steps of 360/7 degrees).",
  "help.12": "<b>Live MIDI output</b>: <i>Enable MIDI</i> asks for access to the ports (Chrome, Edge or Firefox; not Safari), then pick the output. Firefox does not offer Web MIDI on a page opened from <code>file://</code>: run <code>python3 -m http.server</code> in the folder and open <code>http://localhost:8000</code>. Each hexagon has its channel (A = 1 by default). Untick <i>Internal sound</i> in the Sound menu to hear only the synth.",
  "help.13": "<b>Recording</b> (File menu): <i>Record MIDI</i> starts recording the notes (Pause does not stop it); <i>Save the recording</i> stops it and downloads <code>name-date.mid</code> (one track per hexagon, with its channel, one step = an eighth note). <i>Record audio</i> does the same for the internal sound, as <code>.flac</code> (lossless) or <code>.wav</code>.",
  "help.14": "<b>Setup</b> (File menu): the name is prefilled with <code>hexacorde_date_time</code>. <i>Save</i> keeps the layout, lines, scales, channels, rotations, sound and settings in the browser memory; <i>.json file</i> downloads it, <i>Open...</i> reloads it; <i>Text / Copy</i> writes it as text and <i>Apply</i> loads the text pasted in the box. Pulses in flight are not saved.",
  "help.15": "<b>Mutation</b> (Settings): a pulse of polarity opposite to the side it hits flips that line. <b>Theme</b> and <b>language</b> (ENG / FRA, top right) are remembered by the browser.",
  "midi.chan": "Channels",
  "midi.chan.indiv": "Individual (per hexagon)",
  "midi.chan.same": "Same channel for all",
  "midi.chan.title": "All hexagons on one MIDI channel, or each on its own (set in the Hexagrams menu or right-click)",
  "snd.for": "Edit the sound of",
  "snd.hint": "A channel marked ● has its own sound, used by the hexagrams on that channel. Without one, the all-channels sound is used.",
  "snd.allch": "All channels (default)",
  "snd.ch": "Channel {0}",
  "snd.preset": "Instrument",
  "snd.preset.ph": "(choose...)",
  "snd.inherit": "Use the all-channels sound",
  "snd.fmr.title": "FM: frequency ratio of the modulator (× the note frequency)",
  "snd.fmi.title": "FM: modulation index (brightness)",
  "wave.fm": "FM (2 operators)",
  "preset.lead": "Square lead",
  "preset.soft": "Soft sine",
  "preset.bass": "Saw bass",
  "preset.pluck": "Pluck",
  "preset.pad": "Pad",
  "preset.bell": "Bell",
  "preset.organ": "Organ",
  "preset.brass": "Brass",
  "preset.fmbell": "FM bell",
  "preset.fmep": "FM electric piano",
  "preset.fmbass": "FM bass",
  "preset.fmbrass": "FM brass",
  "preset.fmmarimba": "FM marimba",
  "preset.fmpad": "FM pad",
  "midi.inst": "Instruments (program change)",
  "midi.inst.hint": "Instrument of each MIDI channel on the external synth (General MIDI names; on other synths only the number counts). Sent when the output changes and at each Play, and written in the MIDI file.",
  "midi.inst.none": "(not sent)",
});
