//: Textes de l'interface en français
Object.assign(I18N.fr, {
  "play": "Jouer",
  "pause": "Pause",
  "silence": "Silence",
  "silence.title": "Efface toutes les impulsions en vol",
  "step": "Pas",
  "volume": "Volume",
  "bpm.title": "Un pas = une croche : BPM = 30000 / pas en ms",
  "status": "pas {0} · impulsions {1}",
  "status.midi": " · MIDI {0} notes",
  "status.audio": " · audio {0} s",
  "status.stopped": " (arrêté)",
  "grid.aria": "Grille {0}x{1} d'hexagrammes",
  "menu.tonality": "Tonalité",
  "menu.hexagrams": "Hexagrammes",
  "menu.settings": "Réglages",
  "menu.sound": "Son",
  "menu.midi": "MIDI",
  "menu.file": "Fichier",
  "menu.draw": "Tirage",
  "menu.help": "Aide",
  "tonic": "Tonique",
  "octave": "Octave",
  "octave.title": "Octave de base : décale tous les sons",
  "scaleBase": "Gamme",
  "scaleBase.title": "Gamme de base : appliquée à tous les hexagrammes et utilisée pour les nouveaux",
  "tonality.hint": "La tonique et l'octave transposent tout. Chaque hexagramme peut aussi avoir les siens (menu Hexagrammes ou clic droit).",
  "tonic.global": "tonique globale",
  "set.range": "Portée du trait brisé",
  "set.mutate": "Mutation des traits",
  "set.rotAll": "↻ tous",
  "set.rotAll.title": "Rotation de 60° à chaque pas, pour tous",
  "set.uniform": "Octave uniforme",
  "set.uniform.title": "Même octave sur toutes les rangées (sinon la grille couvre 3 octaves, rangées basses graves)",
  "set.theme": "Thème",
  "theme.dark": "Sombre",
  "theme.light": "Clair",
  "theme.sepia": "Sépia",
  "theme.green": "Vert",
  "snd.internal": "Son interne",
  "snd.wave": "Onde",
  "snd.envTitle": "Glisser les points : A, D + S, R",
  "snd.filter": "Filtre",
  "snd.envDepth.title": "Profondeur de l'enveloppe qui ouvre le filtre (suit A D S R)",
  "snd.reset": "Son par défaut",
  "wave.square": "carré",
  "wave.triangle": "triangle",
  "wave.sawtooth": "dent de scie",
  "wave.sine": "sinus",
  "filter.lowpass": "passe-bas",
  "filter.highpass": "passe-haut",
  "filter.bandpass": "passe-bande",
  "filter.notch": "coupe-bande",
  "midi.enable": "Activer le MIDI",
  "midi.noout": "(aucune sortie)",
  "midi.none": "aucune sortie MIDI détectée",
  "midi.denied": "accès MIDI refusé",
  "midi.nofile": "Web MIDI absent en file:// (Firefox) : servir la page, voir l'aide",
  "midi.unavail": "Web MIDI indisponible dans ce navigateur (essayer Chrome, Edge ou Firefox)",
  "file.rec": "Enregistrement",
  "file.names": "Nom des fichiers",
  "file.setup": "Setup",
  "rec.midi": "Enregistrer le MIDI",
  "rec.midi.title": "Enregistre les notes (jusqu'à la sauvegarde)",
  "rec.save": "Sauvegarder l'enregistrement",
  "rec.save.midi.title": "Arrête l'enregistrement et télécharge le fichier .mid",
  "rec.audio": "Enregistrer l'audio",
  "rec.audio.title": "Enregistre le son interne (jusqu'à la sauvegarde)",
  "afmt.title": "Format du fichier",
  "rec.save.audio.title": "Arrête l'enregistrement et télécharge le fichier audio",
  "recmsg.midi.on": "Enregistrement MIDI en cours.",
  "recmsg.midi.off": "Enregistrement MIDI arrêté : il reste à sauvegarder.",
  "recmsg.midi.saved": "Fichier MIDI téléchargé.",
  "recmsg.midi.none": "Rien à sauvegarder : aucune note enregistrée.",
  "recmsg.audio.on": "Enregistrement audio en cours.",
  "recmsg.audio.wait": "Enregistrement audio en cours (il commence au premier Jouer).",
  "recmsg.audio.off": "Enregistrement audio arrêté : il reste à sauvegarder.",
  "recmsg.audio.none": "Rien à sauvegarder : aucun son enregistré.",
  "recmsg.audio.saved": "Fichier .{0} téléchargé ({1} s).",
  "setup.name.title": "Nom du setup",
  "setup.save": "Sauver",
  "setup.save.title": "Garder dans la mémoire du navigateur",
  "setup.load": "Charger",
  "setup.del": "Suppr.",
  "setup.file": "Fichier .json",
  "setup.file.title": "Télécharger un fichier .json",
  "setup.open": "Ouvrir...",
  "setup.open.title": "Ouvrir un fichier .json ou .txt",
  "setup.text.ph": "Le setup en texte : copier / coller ici",
  "setup.copy": "Texte / Copier",
  "setup.copy.title": "Écrit le setup courant dans la zone et le copie",
  "setup.apply": "Appliquer",
  "setup.apply.title": "Charger le setup écrit dans la zone",
  "setup.empty": "(rien en mémoire)",
  "setup.text": "Texte",
  "setup.msg.error": "Erreur : {0}",
  "setup.msg.loaded": "{0} chargé.",
  "setup.msg.saved": "« {0} » gardé en mémoire.",
  "setup.msg.nostore": "Mémoire du navigateur inaccessible : utiliser le fichier ou le texte.",
  "setup.msg.nothing": "Rien à charger.",
  "setup.msg.deleted": "« {0} » supprimé de la mémoire.",
  "setup.msg.file": "Fichier {0}.json téléchargé.",
  "setup.msg.copied": "Texte copié dans le presse-papiers.",
  "setup.msg.manual": "Texte écrit dans la zone : le copier à la main (Ctrl+C).",
  "err.json": "texte illisible (JSON invalide)",
  "err.notsetup": "ce n'est pas un setup Hexacorde",
  "err.max": "{0} hexagrammes au plus",
  "err.pos": "{0} : position invalide (entiers de 0 à {1} pour la colonne, de 0 à {2} pour la ligne)",
  "err.occupied": "{0} : position déjà occupée",
  "err.lines": "{0} : \"traits\" (6 ou 7 chiffres 0 ou 1) ou \"numero\" (1 à 64) attendu",
  "err.chan": "{0} : canal de 1 à 16",
  "err.speed": "{0} : vitesse inconnue \"{1}\" (x1 x2 x3 /2 /3 /4 /8)",
  "err.angle": "{0} : angle multiple de 60",
  "err.notes": "{0} : notes : \"plein\" et \"brise\" = autant de valeurs que de traits (6 ou 7), de 0 à 23 demi-tons (null = silence)",
  "err.scale": "{0} : gamme inconnue \"{1}\"",
  "draw.random": "Tirage des traits au hasard",
  "draw.random.title": "Tire au hasard les traits de tous les hexagrammes",
  "draw.scatter": "Placement au hasard",
  "draw.scatter.title": "Déplace les hexagrammes sur des points au hasard de la grille",
  "hex.title": "Hexagramme",
  "act.title": "Actif : décocher pour griser l'hexagone",
  "del.title": "Supprimer cet hexagone",
  "scale.title": "Gamme",
  "chan.title": "Canal MIDI",
  "stonic.title": "Tonique de cet hexagone",
  "soct.title": "Octave de cet hexagone (en plus de l'octave globale)",
  "rot": "rot.",
  "rot.title": "Faire tourner cet hexagone",
  "dir.title": "Sens de rotation",
  "spd.title": "Vitesse de rotation",
  "reset": "Réinit.",
  "reset.title": "Remettre cet hexagramme à sa forme de départ",
  "loop.every": "amorce tous les",
  "steps": "pas",
  "loop.title": "Amorcer une note de cet hexagone tous les N pas",
  "seven": "7e côté",
  "seven.title": "Ajoute un 7e côté : l'hexagone devient un heptagone",
  "m.hex": "Hexagramme",
  "m.scale": "Gamme",
  "m.chan": "Canal MIDI",
  "m.tonic": "Tonique",
  "m.oct": "Octave",
  "m.rot": "Rotation",
  "m.rot.active": "active",
  "m.sides": "Côtés",
  "m.seven": "7e côté (heptagone)",
  "m.loop": "Amorce",
  "m.loop.every": "tous les",
  "m.turn": "Tourner",
  "m.ccw.title": "Tourner de 60° dans le sens antihoraire",
  "m.cw.title": "Tourner de 60° dans le sens horaire",
  "m.custom": "Notes personnalisées",
  "m.hint": "Gamme {0}, tonique {1}",
  "m.line": "trait",
  "m.solid": "plein",
  "m.broken": "brisé",
  "m.silence": "· silence",
  "m.tonicMark": " (tonique)",
  "m.fill": "Reprendre la gamme",
  "m.fill.title": "Copie les notes de la gamme actuelle",
  "m.shuffle": "Mélanger l'ordre",
  "m.shuffle.title": "Change au hasard l'ordre des notes entre les traits, la note en trop de la gamme comprise",
  "m.deactivate": "Désactiver",
  "m.activate": "Activer",
  "m.deact.title": "Griser l'hexagone : il ne joue ni ne reçoit",
  "m.delete": "Supprimer",
  "m.close": "Fermer",
  "sel.title": "{0} hexagrammes sélectionnés",
  "sel.clear": "Désélectionner",
  "board.title": "Grille {0}x{1}",
  "board.add": "Nouvel hexagramme ici",
  "board.add.title": "Ajoute un hexagramme tiré au hasard sur le point libre le plus proche",
  "board.size": "Taille",
  "board.cols": "colonnes",
  "board.rows": "lignes",
  "board.apply": "Appliquer",
  "board.hint": "colonnes x lignes, de {0} à {1}",
  "board.nofit": "Impossible : un hexagone est hors de la nouvelle grille (tailles de {0} à {1})",
  "board.delsel": "Supprimer la sélection ({0})",
  "board.delsel.title": "Supprime les hexagrammes sélectionnés",
  "scale.chromatique": "Chromatique",
  "scale.chromatique.s": "chr",
  "scale.majeur": "Majeur",
  "scale.majeur.s": "maj",
  "scale.mineur": "Mineur naturel",
  "scale.mineur.s": "min",
  "scale.dorien": "Dorien",
  "scale.dorien.s": "dor",
  "scale.phrygien": "Phrygien",
  "scale.phrygien.s": "phr",
  "scale.lydien": "Lydien",
  "scale.lydien.s": "lyd",
  "scale.mixolydien": "Mixolydien",
  "scale.mixolydien.s": "mix",
  "scale.locrien": "Locrien",
  "scale.locrien.s": "loc",
  "scale.mineurharm": "Mineur harmonique",
  "scale.mineurharm.s": "hmi",
  "scale.mineurmel": "Mineur mélodique",
  "scale.mineurmel.s": "mmi",
  "scale.tons": "Par tons",
  "scale.tons.s": "ton",
  "scale.blues": "Blues",
  "scale.blues.s": "blu",
  "scale.pentamajeur": "Pentatonique majeure",
  "scale.pentamajeur.s": "pM",
  "scale.pentamineur": "Pentatonique mineure",
  "scale.pentamineur.s": "pm",
  "scale.hongrois": "Mineur hongrois",
  "scale.hongrois.s": "hon",
  "scale.phrygiendom": "Phrygien dominant",
  "scale.phrygiendom.s": "pdo",
  "scale.doubleharm": "Double harmonique",
  "scale.doubleharm.s": "dbh",
  "scale.dim12": "Diminuée (demi-ton / ton)",
  "scale.dim12.s": "dm1",
  "scale.dim21": "Diminuée (ton / demi-ton)",
  "scale.dim21.s": "dm2",
  "scale.insen": "In sen (japonaise)",
  "scale.insen.s": "ins",
  "scale.hirajoshi": "Hirajoshi",
  "scale.hirajoshi.s": "hir",
  "scale.bebop": "Bebop dominante",
  "scale.bebop.s": "beb",
  "scale.augmentee": "Augmentée",
  "scale.augmentee.s": "aug",
  "help.1": "<b>Cliquer</b> un hexagone : l'amorcer (lance l'horloge). <b>Glisser</b> son corps : le déplacer sur un point libre de la grille. <b>Cliquer un trait</b> : le basculer plein / brisé. <b>Glisser un trait</b> : fait tourner l'hexagone par crans de 60° ; la <b>molette</b> aussi.",
  "help.2": "<b>Notes (chromatique)</b> : trait 1 (en haut) do / do#, puis sens horaire ré / ré#, mi / fa, fa# / sol, sol# / la, la# / si. Plein = note naturelle, brisé = note + 1 demi-ton. L'octave dépend de la rangée de la grille.",
  "help.3": "<b>Notes (gammes)</b> : le côté k joue le degré k+1 de la gamme (au-delà de la dernière note, on repart à l'octave). Trait plein : la note est jouée et renvoyée. Trait brisé : silence, rien n'est renvoyé, mais les impulsions reçues le traversent toujours. Il y a 23 gammes.",
  "help.4": "<b>Envoi</b> : chaque trait joué envoie une impulsion dans sa direction, vers le premier hexagone du secteur. Plus il est loin, plus elle met de pas.",
  "help.5": "<b>Trait plein</b> : impulsion forte, portée illimitée, et à l'arrivée le côté touché rebondit (l'hexagone se met à jouer). <b>Trait brisé</b> : impulsion douce, portée courte, et à l'arrivée elle traverse l'hexagone sans le faire sonner.",
  "help.6": "<b>Nom</b> : chaque hexagramme affiche son numéro et son nom du Yi Jing (ordre du Roi Wen). Le trait 1 de l'hexagone est lu comme le premier trait de l'hexagramme (celui du bas dans la tradition), les traits 4 à 6 forment le trigramme supérieur.",
  "help.7": "<b>Clic droit sur un hexagone</b> : tous ses réglages (hexagramme, gamme, canal, tonique, octave, rotation, 7e côté, amorce tous les N pas, Réinit.), un cran de 60°, les <b>notes personnalisées</b> (on choisit la note du trait plein et du trait brisé de chaque côté, silence permis ; les notes de la gamme sont marquées ● et colorées), <b>Reprendre la gamme</b>, <b>Mélanger l'ordre</b>, et <b>Désactiver</b> (grisé : il ne joue ni ne reçoit) ou <b>Supprimer</b>.",
  "help.8": "<b>Clic droit sur la grille</b> : ajouter un hexagramme (traits au hasard, gamme et tonique globales) sur le point libre le plus proche, ou fixer la taille de la grille (colonnes x lignes, de 3 à 12). La grille couvre 3 octaves, rangées basses graves (cocher <i>Octave uniforme</i> dans Réglages pour la même octave partout).",
  "help.9": "<b>Sélection</b> : tirer un rectangle sur le fond de la grille sélectionne plusieurs hexagrammes (Maj ajoute, un clic sur le fond désélectionne). Clic droit sur l'un d'eux : supprimer, désactiver ou activer toute la sélection ; la touche Suppr supprime aussi.",
  "help.10": "Menu <b>Tonalité</b> : tonique, octave et gamme de base pour tout. Choisir une gamme ici l'applique à tous les hexagrammes et à ceux ajoutés plus tard. Chaque hexagramme peut avoir sa propre tonique et une octave en plus.",
  "help.11": "<b>Rotation</b> (par hexagone, menu Hexagrammes) : l'hexagone tourne par pas de 60°. Vitesse ×1 = un pas de 60° à chaque pas d'horloge, ×2 et ×3 = deux ou trois pas, ÷2 à ÷8 = un pas tous les 2 à 8 pas d'horloge. Chaque trait garde sa note, mais sa direction d'envoi et le trait touché à la réception changent. <b>7e côté</b> : l'hexagone devient un heptagone (crans de 360/7 degrés).",
  "help.12": "<b>Sortie MIDI en direct</b> : « Activer le MIDI » demande l'accès aux ports (Chrome, Edge ou Firefox ; pas Safari), puis on choisit la sortie. Firefox n'offre pas Web MIDI sur une page ouverte en <code>file://</code> : lancer <code>python3 -m http.server</code> dans le dossier et ouvrir <code>http://localhost:8000</code>. Chaque hexagone a son canal (A = 1 par défaut). Décochez « Son interne » dans le menu Son pour n'entendre que le synthé.",
  "help.13": "<b>Enregistrement</b> (menu Fichier) : « Enregistrer le MIDI » lance l'enregistrement des notes (la Pause ne l'arrête pas) ; « Sauvegarder l'enregistrement » l'arrête et télécharge <code>nom-date.mid</code> (une piste par hexagone, avec son canal, un pas = une croche). « Enregistrer l'audio » fait pareil pour le son interne, en <code>.flac</code> (sans perte) ou <code>.wav</code>.",
  "help.14": "<b>Setup</b> (menu Fichier) : le nom est pré-rempli avec <code>hexacorde_date_heure</code>. « Sauver » garde la disposition, les traits, les gammes, canaux, rotations, le son et les réglages dans la mémoire du navigateur ; « Fichier .json » la télécharge, « Ouvrir... » la recharge ; « Texte / Copier » écrit le setup en texte et « Appliquer » charge le texte collé dans la zone. Les impulsions en cours ne sont pas sauvegardées.",
  "help.15": "<b>Mutation</b> (Réglages) : une impulsion de polarité opposée au côté touché inverse ce trait. Le <b>thème</b> et la <b>langue</b> (ENG / FRA, en haut à droite) sont retenus par le navigateur.",
  "midi.chan": "Canaux",
  "midi.chan.indiv": "Individuels (par hexagone)",
  "midi.chan.same": "Même canal pour tous",
  "midi.chan.title": "Tous les hexagones sur un seul canal MIDI, ou chacun le sien (réglé dans le menu Hexagrammes ou le clic droit)",
  "snd.for": "Éditer le son de",
  "snd.hint": "Un canal marqué ● a son propre son, utilisé par les hexagrammes de ce canal. Sinon, le son de tous les canaux est utilisé.",
  "snd.allch": "Tous les canaux (défaut)",
  "snd.ch": "Canal {0}",
  "snd.preset": "Instrument",
  "snd.preset.ph": "(choisir...)",
  "snd.inherit": "Reprendre le son de tous les canaux",
  "snd.fmr.title": "FM : rapport de fréquence du modulateur (× la fréquence de la note)",
  "snd.fmi.title": "FM : indice de modulation (brillance)",
  "wave.fm": "FM (2 opérateurs)",
  "preset.lead": "Lead carré",
  "preset.soft": "Sinus doux",
  "preset.bass": "Basse dent de scie",
  "preset.pluck": "Pizzicato",
  "preset.pad": "Nappe",
  "preset.bell": "Cloche",
  "preset.organ": "Orgue",
  "preset.brass": "Cuivres",
  "preset.fmbell": "Cloche FM",
  "preset.fmep": "Piano électrique FM",
  "preset.fmbass": "Basse FM",
  "preset.fmbrass": "Cuivres FM",
  "preset.fmmarimba": "Marimba FM",
  "preset.fmpad": "Nappe FM",
  "midi.inst": "Instruments (program change)",
  "midi.inst.hint": "Instrument de chaque canal MIDI sur le synthé externe (noms General MIDI ; sur un autre synthé, seul le numéro compte). Envoyé au changement de sortie et à chaque Jouer, et écrit dans le fichier MIDI.",
  "midi.inst.none": "(non envoyé)",
});
